CREATE DATABASE IF NOT EXISTS music;

USE music;

CREATE TABLE playlist (
  id INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  song VARCHAR(50) NOT NULL,
  artist VARCHAR(20) NOT NULL,
  album VARCHAR(40) NOT NULL,
  genre VARCHAR(15) NULL,
  year INT(4) NOT NULL
);